# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tan Ho Huu
title: Software Engineer
email: huutan.dev@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  hhuutan
linkedin_username: hhuutan

# About Section
about_title: Brief
about_profile_image: images/profile.jpg
about_content: |
  Dedicated and efficient Software Engineer with 4+ years experience in software development from planning, designing to implementing, web applications and data synchronization.

  Insightful knowledge of .NET technology, OOP Analysis, SOLID Principle.

  Receptive in new technologies, flexible in working style and self-directed settings.

content:

  - title: Education
    layout: list
    content:
      - layout: left
        title: Cantho University
        caption: 2014 - 2018
        sub_title: BSc Information System
        description: |
          <ul>
            <li>During my time at school I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines.</li>
            <li>I was also honored to receive the 2016 Outstanding Student Award, named in the school's list of excellent students that year, as well as receive a lot of respect and love from friends and teachers.</li>
            <li>I have spent a lot of my free time as a volunteer for volunteer programs with many humanistic meanings, helping the community such as green summer (Mùa hè xanh), red journey (Hành trình đỏ), the mid-autumn festival for children (Trung thu cho em), ...</li>
          </ul>

  - title: Experience
    layout: list
    content:    
      - layout: left
        title: NFQ Asia
        sub_title: Software Engineering (Mid+)
        caption: Aug 2021 - Present
        description: |
            <ul>
              <li>Participated in developing a startup project in the E-commerce domain from planning, designing, implementing to deploying the application.</li>
              <li>Directly communicates in both technical/business domain discussions with the client's development team in Germany.</li>
              <li>Researched many new technologies such as Azure Function 4 (.NET 6), CosmosDB, MySQL, Azure Service Bus,... to apply to the project.</li>
              <li>Supported team members in debugging and exploring their abilities, helping them better on coding and thinking skills.</li>
              <li>Used Scrum model with support from Azure DevOps to manage PBI, features, tasks, bugs,... and deployments.</li>
              
              <li>Technologies:
                <mark>.NET 6</mark> <mark>Azure Function 4</mark> <mark>CosmosDB</mark> <mark>MySQL</mark> <mark>MySQL</mark> <mark>Azure DevOps</mark>
                <mark>Azure Service Bus</mark> <mark>Azure Blob Storage</mark> <mark>Docker</mark> <mark>Git</mark>
              </li>
            </ul>

      - layout: left
        title: FPT Software
        sub_title: Software Engineering (Juni, Mid)
        caption: May 2018 - May 2019
        description: |
          <ul>
            <li>Was a Junior developer after graduation, I had a good start in my career here under the guidance of experienced people, have been involved in potential projects as well as access to new technologies, potential customers.</li>
            <li>My main programming language: C#. Participated in many projects both web applications (APS.NET core/Framework) and desktop applications (Winform, WPF, Java), supporting many customers to develop their products, complete on schedule and goals.</li>
            <li>Was a key member of development team in serveral projects.</li>
            <li>Learned some new programming languages: Python, JavaScrip, Xtend,... and several related technologies to handle the new projects.</li>
            <li>Independent worked directly in communication and development with a foreigner customer (Malaysian).</li>
            <li>Have worked with Scrum, Agile models in some projects.</li> 
            <li>Worked clients: Japan, USA, Malaysia.</li>
            <li>Worked domains: OCR, Data synchronization, AUTOSAR Tools, PDF viewer, Oil & Gas, ETL,...</li>
            <li> Technologies:
              <mark>ASP.NET 4.5</mark> <mark>ASP.NET Core 2/3/5</mark> <mark>Java</mark> <mark>Python</mark> <mark>WPF</mark> <mark>Winform</mark>
              <mark>Extend</mark> <mark>Docker</mark> <mark>JavaScript</mark> <mark>JQuery</mark> <mark>Entity Framework</mark>
              <mark>LINQ</mark> <mark>OracleDB</mark> <mark>MS SQL</mark> <mark>Posgresql</mark> <mark>MongoDB</mark> <mark>Elastic Search</mark>
              <mark>Redis Cache</mark> <mark>Git</mark> <mark>SVN</mark> <mark>Azure DevOps</mark> <mark>Jira</mark> <mark>Redmine</mark>
            </li>
          </ul>

  - title: Typical Projects
    layout: list
    content:
      - layout: left
        title: Content Parsing Engine
        sub_title: Jan 2019 – Aug 2019
        caption: 17 members, USA
        description: |
          A web application with a medium backend system that makes it easier for customers to extract data from multiple types of documents from non-copyable like images, PDF,... to copyable based on Abbyy FineReader Engine.

          Using the machine learning algorithms to catogirize the documents and synchronizing them to the cloud storages, like Kintone, DrChrono, QuickBooks, …

          My responsibility:
          <ul>
            <li>Discussed with BA & the Techlead to come out the solution for the features related to the UI, user activities and data synchronization.</li>
            <li>Did planning, designing database, code structure and implement the solution with less support from others.</li>
            <li>Worked independent to create the adapters to synchronize data from the system into Cloud Storages such as Kintone, QuickBooks, Google Drive,...</li>
          </ul>

          Technologies: <mark>ASP.NET Core 2.2</mark>, <mark>ABBYY SDK</mark>, <mark>RabbitMQ</mark>, <mark>Redis Cache</mark>, <mark>Elastic Search</mark>, <mark>MSSQL</mark>, <mark>MongoDB</mark>, <mark>JQuery</mark>, <mark>Bootstrap 3</mark>, <mark>Docker</mark>

      - layout: left
        title: Floaters
        sub_title: Feb 2020 - Feb 2021
        caption: 10 members, Malaysian
        description: |
          Our team was developing a system to manage floaters over the sea of Petronas. 
          
          This systems allows user to track real-time status of each platform. 
          It also provides the future plan for inspecting if any one of these having issue.
          Excel/PDF export functionality allows user to export data from the system. This system uses IP frameworks of Petronas.

          My responsibility:
          <ul>
            <li>Directly worked with the client team.</li>
            <li>Implemented functions giving by team lead and BA for both frontend and backend side.</li>
            <li>In tight collaboration with BA, studied all the project requirements to design and implement solution.</li>
            <li>Managed, developed and delivered complex data migration.</li>
          </ul>

          Technologies: <mark>ASP MVC 4</mark>, <mark>EF</mark>, <mark>JQuery</mark>, <mark>MSSQL</mark>, <mark>Azure DevOps</mark>

      - layout: left
        title: Go Dashboard
        sub_title: Oct 2020 - Feb 2021
        caption: 10 members, Malaysian
        description: |
          A web application that monitor the output of oil and gas extraction sites around the world.
          This system gets the data from other extenal api to calculate, analysic and show the numbers, charts and info cards to 
          the dashboard UI almost realtime.

          My responsibility:
          <ul>
            <li>Directly worked with the client team.</li>
            <li>In tight collaboration with BA, team leader to build the backend application from scratch following the user stories.</li>
            <li>Studied all the project requirements to design the database, function details and implement solutions.</li>
          </ul>

          Technologies: <mark>ASP MVC 4</mark>, <mark>EF</mark>, <mark>JQuery</mark>, <mark>MSSQL</mark>, <mark>Azure DevOps</mark>

      - layout: left
        title: Data Exchange Engine
        sub_title: Oct 2021 - Present
        caption: 7 members, Germany
        description: |
          This's a middleware system between ERPs and the Marketplaces that allow the end clients can exchange data from a local sales system through to online sales systems quickly and efficiently.

          The system also supports tools to convert data between different regions, they can be languages, currencies, SEO keywords,...

          This is a startup project, we have built it from zero.

          My responsibility:
          <ul>
              <li>Participated in developing a startup project in the E-commerce domain from planning, designing, implementing to deploying the application.</li>
              <li>Directly communicates in both technical/business domain, discussions with the client's team to findout the best solution.</li>
              <li>Researched many new technologies such as Azure Function 4 (.NET 6), CosmosDB, MySQL, Azce Bus,... to apply to the project.</li>
              <li>Supported team members in debugging and exploring their abilities, helping them better on coding and thinking skills.</li>
          </ul>

          Technologies: <mark>.NET 6</mark>, <mark>Azure Function 4</mark>, <mark>CosmosDB</mark>, <mark>MySQL</mark>, <mark>MySQL</mark>, <mark>Azure DevOps</mark>, 
          <mark>Azure Service Bus</mark>, <mark>Azure Blob Storage</mark>, <mark>Docker</mark>

  - title: When I am not a Developer
    layout: text
    content: |
      Alongside my interests in software engineer some of my other interests and hobbies are:
      - Traveling
      - Riding
      - Reading
      - Meditation
      - MCU Fan (Movie)

footer_show_references: false

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
